Repository sjohnston00/HotshotTournaments, pull requests merged in 2021-03, with the labels that each got.

#7 Fix When deleting a tournament, an error message toast is sent to the view, even though the tournament is successfully deleted #5
  src/controllers/tournamentsController.js
Labels: bug

#17 Convert if statement in tournament type validation to switch
  src/controllers/tournamentsController.js
Labels: good first issue

#30 Update My Tournament view
  package-lock.json
  package.json
  src/views/partials/footer.mustache
  src/views/tournaments/myTournaments.mustache
Labels: enhancement

#31 Split my tournaments view
  src/controllers/tournamentsController.js
  src/views/tournaments/myTournaments.mustache
  src/views/tournaments/tournamentCard.mustache
Labels: enhancement

#51 Replace alerts with toasts
  src/content/scripts/showToasts.js
  src/views/partials/head.mustache
  src/views/partials/messages.mustache
  src/views/tournaments/myTournaments.mustache
Labels: enhancement

#63 Delete user messages
  src/content/scripts/tournamentMessaging.js
  src/controllers/tournamentsController.js
  src/routes/messages.js
  src/socket.js
  src/views/partials/tournaments/tournamentMessages.mustache
Labels: enhancement

#65 Implement (ugly) timestamps
  .gitignore
  package-lock.json
  src/content/css/shared/bootstrapOverrides.css
  src/content/css/shared/messagePanel.css
  src/content/scripts/tournamentMessaging.js
  src/controllers/messagesController.js
  src/views/partials/tournaments/tournamentMessages.mustache
Labels: enhancement
